name: First Workflow

on: push

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
    - name: step1
      run: echo "this is step1"
    - name: step2
      run: echo "ths is step2"
    - name: step3
      run: |
       echo "this is multiline command"
       echo "this is the example"
    
