name: My Workflow

on:
  push:
    branches:
      - main


jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
    - name: step1
      run: echo "this is $my_name"
      env: 
         my_name: malini
    - name: step2
      run: echo "this is step 2"
    - name: step3
      run: |
       echo "this is multiline command"
       echo "this is the example"
    
